version: '3.8'
services:
  oidc_client:
    build:
      context: ./
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
      - "5000:5000"
      - "5001:5001"
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=keycloak_user
      - KEYCLOAK_PASSWORD=keycloak_password
